name: 'devcard'
description: 'GitHub Action to download the devcard from daily.dev'
author: 'Ole-Martin Bratteng'
inputs:
  hash:
    description: 'The hash of the devcard'
    required: true

  token:
    description: GitHub Token used to commit the devcard
    default: ${{ github.token }}
    required: false

  commit_branch:
    description: Branch used to commit the devcard
    default: ""
    required: false

  commit_message:
    description: Commit message
    default: Update ${filename}
    required: false

  commit_filename:
    description: Filename to save devcard to
    default: devcard.svg
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
