name: test-local-action
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "Dockerfile"
      - "action.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  svg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2.3.4

      -
        name: Run location action
        uses: ./
        with:
          hash: ${{ secrets.DEVCARD_HASH }}
          commit_branch: devcard
          commit_message: "chore: update ${filename}"

  png:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2.3.4

      -
        name: Run location action
        uses: ./
        with:
          hash: ${{ secrets.DEVCARD_HASH }}
          commit_branch: devcard
          commit_message: "chore: update ${filename}"
          commit_filename: devcard.png
